### ISSUE TITLE
테스트 학습 오류

### ISSUE THREAD

**Issue by heon0120** [NellLucas/classcard_hack#2]
Traceback (most recent call last):
  File "C:\Users\user\Desktop\classcard atuto2\main.py", line 221, in <module>
    if da_e.index(cash_d) == da_k.index(cash_dby[j]):
                             ^^^^^^^^^^^^^^^^^^^^^^^
ValueError: '바깥쪽의, 외부의, 외부' is not in list

테스트학습을 하는데 위와같은 오류가 뜹니다.
로그인과 세트페이지 테스트학습 시작페이지까지 접속은 가능한데 문제가나오면 클릭을 하지 못하는것 같습니다. 한달전에는 정상작동했는데 이러한 지금이러한 에러가 뜨네요.
클래스카드가 업데이트를 했나보네요. 수정부탁드립니다.

**Comment by NellLucas** [comment]
클래스카드 업데이트로 인해 수정된 구조를 반영했습니다.
- 변경된 XPath 주소 수정
- 변경된 단어 데이터 구조에 맞게 수정
- 크롤러 감지 코드 우회(AutomationControlled)
- Etc.. #

**Comment by NellLucas** [comment]
클래스카드 업데이트로 인해 수정된 구조를 반영했습니다.
- 변경된 XPath 주소 수정
- 변경된 단어 데이터 구조에 맞게 수정
- 크롤러 감지 코드 우회(AutomationControlled)
- Etc..
