### ISSUE TITLE
문장 관련 에러

### ISSUE THREAD

**Issue by goomantop** [NellLucas/classcard_hack#4]
1
Traceback (most recent call last):
  File "C:\Program Files (x86)\Google\classcard_hack-main\main.py", line 178, in <module>
    main()
  File "C:\Program Files (x86)\Google\classcard_hack-main\main.py", line 122, in main
    word_d = word_get(driver, num_d) # 단어 데이터 수집
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files (x86)\Google\classcard_hack-main\utility.py", line 17, in word_get
    url = driver.find_element(By.XPATH, f"//*[@id='tab_set_all']/div[2]/div[{i}]/div[4]/div[1]/div[3]/a").get_attribute('data-src')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\김태희\AppData\Roaming\Python\Python312\site-packages\selenium\webdriver\remote\webdriver.py", line 741, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\김태희\AppData\Roaming\Python\Python312\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\김태희\AppData\Roaming\Python\Python312\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id='tab_set_all']/div[2]/div[1]/div[4]/div[1]/div[3]/a"}
  (Session info: chrome=129.0.6668.70); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
        GetHandleVerifier [0x00007FF720FAB125+29573]
        (No symbol) [0x00007FF720F1FF50]
        (No symbol) [0x00007FF720DDB6EA]
        (No symbol) [0x00007FF720E2F815]
        (No symbol) [0x00007FF720E2FA6C]
        (No symbol) [0x00007FF720E7B917]
        (No symbol) [0x00007FF720E5733F]
        (No symbol) [0x00007FF720E786BC]
        (No symbol) [0x00007FF720E570A3]
        (No symbol) [0x00007FF720E212DF]
        (No symbol) [0x00007FF720E22441]
        GetHandleVerifier [0x00007FF7212DC76D+3377613]
        GetHandleVerifier [0x00007FF721327B67+3685831]
        GetHandleVerifier [0x00007FF72131CF8B+3641835]
        GetHandleVerifier [0x00007FF72106B2A6+816390]
        (No symbol) [0x00007FF720F2B25F]
        (No symbol) [0x00007FF720F27084]
        (No symbol) [0x00007FF720F27220]
        (No symbol) [0x00007FF720F1607F]
        BaseThreadInitThunk [0x00007FFBA2C9257D+29]
        RtlUserThreadStart [0x00007FFBA402AF28+40]

제 생각엔 문장 관련 데이터들은 저장을 못하는 에러 같네요

**Comment by NellLucas** [comment]
QuizBattle에 영어 발음을 듣고 선택하는 문제가 있어 오디오 파일을 추출하는 코드를 추가했지만, 위의 오류 코드를 바탕으로 분석했을 때, 발음 파일 자체가 존재하지 않는 단어 세트도 존재하는 듯 합니다.

따라서, 예외 처리를 통해 오디오 파일이 존재하지 않으면 pass하도록 코드를 수정했습니다.
<fix: add exception handling to allow learning even in word sets without pronunciation audio files.>
