### ISSUE TITLE
잘못된 단어 세트

### ISSUE THREAD

**Issue by slayysr** [NellLucas/classcard_hack#5]
요소 찾기에서 막히는데 해결 방법이 있나요?

**Comment by NellLucas** [comment]
정확한 오류 상황을 파악하기 위해 로그를 남겨주세요!!

**Comment by slayysr** [comment]
자동으로 단어와 뜻을 학습 후 테스트 시작 되는걸로 아는데 요소 찾기에서 인식이 안돼요 다른 분들도 그러는거 같던데 ㅜ

요소를 찾는 데 시간이 초과되었습니다: //*[@id='confirmModal']/div[2]/div/div[2]/a[3]
Traceback (most recent call last):
  File "c:\fpsO\fpsO\learning_types\test.py", line 77, in run_test
    if da_e.index(cash_d) == da_k.index(cash_dby[j]):
                             ^^^^^^^^^^^^^^^^^^^^^^^
ValueError: '경계(선), 영역, 한계' is not in list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\fpsO\fpsO\learning_types\test.py", line 86, in run_test
    if da_e.index(cash_d) == da_kn.index(cash_dby[j]):
                             ^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: '경계(선), 영역, 한계' is not in list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\fpsO\fpsO\main.py", line 178, in <module>
    main()
  File "c:\fpsO\fpsO\main.py", line 160, in main
    test.run_test(driver, num_d, da_e, da_k, da_kn, da_ked, time_1)
  File "c:\fpsO\fpsO\learning_types\test.py", line 94, in run_test
    if da_e.index(cash_d) == da_ked.index(cash_dby[j]):
                             ^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: '경계(선), 영역, 한계' is not in list

**Comment by NellLucas** [comment]
가끔씩 단어 세트에 저장된 단어와 테스트 학습에서 나타나는 단어가 다르게 설정된 학습 세트(선생님이 등록한)가 있습니다. 세트마다 단어 전처리 과정을 다르게 설정할 수 없으므로, 단어 세트와 테스트 학습에서 나타나는 단어를 비교해보셔서 utility.py를 적절히 수정한 후 사용하시길 바랍니다!!
